version: '3'

services:
  mod-php:
    build: ./mod-php
    volumes:
    - ..:/approot
    environment:
      LESSCHARSET: utf-8
      PHP_IDE_CONFIG: serverName=keso01
      XDEBUG_CONFIG: remote_autostart=1
    ports:
    - 10080:80
